name: Build & Deploy

on:
  push:
    branches: [ master, main ]

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build API
      - name: Build api image
        run: |
          docker build -f Dockerfile.api -t $REGISTRY/${{ env.OWNER }}/igclone-api:latest .
          docker tag $REGISTRY/${{ env.OWNER }}/igclone-api:latest $REGISTRY/${{ env.OWNER }}/igclone-api:${{ github.sha }}
      - name: Push api image
        run: |
          docker push $REGISTRY/${{ env.OWNER }}/igclone-api:latest
          docker push $REGISTRY/${{ env.OWNER }}/igclone-api:${{ github.sha }}

      # Build WEB
      - name: Build web image
        run: |
          docker build -f Dockerfile.web -t $REGISTRY/${{ env.OWNER }}/igclone-web:latest .
          docker tag $REGISTRY/${{ env.OWNER }}/igclone-web:latest $REGISTRY/${{ env.OWNER }}/igclone-web:${{ github.sha }}
      - name: Push web image
        run: |
          docker push $REGISTRY/${{ env.OWNER }}/igclone-web:latest
          docker push $REGISTRY/${{ env.OWNER }}/igclone-web:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Copy compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/igclone/"

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/igclone
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose pull
            docker compose up -d
            docker image prune -f
